# Generated by Django 5.0.3 on 2024-03-18 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_healthsubsidy_delete_resident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthsubsidy',
            old_name='name',
            new_name='applicant_name',
        ),
        migrations.RenameField(
            model_name='healthsubsidy',
            old_name='health_condition',
            new_name='medical_history',
        ),
        migrations.RemoveField(
            model_name='healthsubsidy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='healthsubsidy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='healthsubsidy',
            name='income',
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 3, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='gender',
            field=models.CharField(default='female', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='insurance_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='policy_holder',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
