# Generated by Django 5.0.3 on 2024-03-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_healthsubsidy_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsubsidy',
            name='applicant_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
