# Generated by Django 5.0.3 on 2024-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_healthsubsidy_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsubsidy',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
