# Generated by Django 5.0.3 on 2024-03-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_healthsubsidy_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsubsidy',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthsubsidy',
            name='applicant_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthsubsidy',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='healthsubsidy',
            name='insurance_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='healthsubsidy',
            name='policy_holder',
            field=models.CharField(default='', max_length=100),
        ),
    ]
