# Generated by Django 5.0.3 on 2024-03-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_healthsubsidy_address_healthsubsidy_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthsubsidy',
            options={'verbose_name_plural': 'Health Subsidies'},
        ),
    ]
