# Generated by Django 5.0.3 on 2024-03-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_healthsubsidy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteManagementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('waste_type', models.CharField(choices=[('general', 'General Waste'), ('recyclable', 'Recyclable Waste'), ('organic', 'Organic Waste')], max_length=20)),
                ('collection_day', models.CharField(max_length=50)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
