# Generated by Django 5.0.3 on 2024-03-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_wastemanagementapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySupportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('reason_for_support', models.TextField()),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
