# Generated by Django 5.0.3 on 2024-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_temporarysupportapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowIncomeSupportApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupation', models.CharField(max_length=100)),
                ('expected_support', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
