# Generated by Django 5.0.3 on 2024-03-20 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_crimereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereport',
            name='report_date',
        ),
    ]
