# Generated by Django 5.0.3 on 2024-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_pensionsupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowincomesupportapplication',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='proof_documents/'),
        ),
    ]
