# Generated by Django 5.0.3 on 2024-03-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_lowincomesupportapplication_proof_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsubsidy',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='income_proof/'),
        ),
    ]
