# Generated by Django 5.0.3 on 2024-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_childcaresupport_income_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='evidence_proof',
            field=models.FileField(blank=True, null=True, upload_to='crime_reports/'),
        ),
    ]
