# Generated by Django 5.0.3 on 2024-04-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_crimereport_evidence_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcaresupport',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='crimereport',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='healthsubsidy',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='localitytaxpayment',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='lowincomesupportapplication',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='pensionsupport',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='temporarysupportapplication',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
        migrations.AddField(
            model_name='wastemanagementapplication',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], default='On Hold', max_length=20),
        ),
    ]
