# Generated by Django 5.0.3 on 2024-04-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_childcaresupport_status_crimereport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcaresupport',
            name='evidence_proof',
            field=models.FileField(blank=True, null=True, upload_to='evidence_proof/'),
        ),
    ]
