# Generated by Django 5.0.3 on 2024-04-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_childcaresupport_evidence_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcaresupport',
            name='evidence_proof',
        ),
    ]
