# Generated by Django 5.0.3 on 2024-04-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
